#define INTERRUPT_EDGE OPTION_REGbits.INTEDG
#define GLOBAL_INTERRUPT INTCONbits.GIE
#define EXTERNAL_INTERRUPT INTCONbits.INTE

#define EXTERNAL_INTERRUPT_FLAG INTCONbits.INTF

#define PORT_CHANGE_INTERRUPT INTCONbits.GPIE
#define PORT_CHANGE_INTERRUPT_FLAG INTCONbits.GPIF

#define INTERRUPT_ON_CHANGE IOCbits.IOC0